// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Scrape Data', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Scrape Data', async function() {
    await driver.get("https://gscivildata.shelbycountytn.gov/pls/gnweb/ck_public_qry_cpty.cp_personcase_setup_idx")
    await driver.switchTo().frame(1)
    await driver.findElement(By.name("partial_ind")).click()
    await driver.findElement(By.name("last_name")).click()
    await driver.findElement(By.name("last_name")).sendKeys("A")
    await driver.findElement(By.name("begin_date")).click()
    await driver.findElement(By.name("begin_date")).sendKeys("01-NOV-2021")
    await driver.findElement(By.css("tr:nth-child(7) > td:nth-child(1)")).click()
    await driver.findElement(By.name("end_date")).click()
    await driver.findElement(By.name("end_date")).sendKeys("14-NOV-2021")
    await driver.findElement(By.name("case_type")).click()
    await driver.findElement(By.css("option:nth-child(17)")).click()
    await driver.findElement(By.css("input:nth-child(4)")).click()
    await driver.switchTo().frame(1)
        // Firefox fails here with "NoSuchWindowError: Browsing context has been discarded"
    vars["ID"] = await driver.findElement(By.css("tr:nth-child(2) > td:nth-child(1)")).getText()
    vars["PartyType"] = await driver.findElement(By.css("tr:nth-child(2) > td:nth-child(4)")).getText()
    vars["FilingDate"] = await driver.findElement(By.css("tr:nth-child(2) > td:nth-child(5)")).getText()
    vars["ID"] = await driver.findElement(By.css("tr:nth-child(3) > td:nth-child(1)")).getText()
  })
})
