// Partically generated by Selenium IDE.
const { Builder, By } = require('selenium-webdriver')

class Scraper {
  async scrapeByFirstLetter(driver, firstLetter) {
    await driver.get("https://gscivildata.shelbycountytn.gov/pls/gnweb/ck_public_qry_cpty.cp_personcase_setup_idx")
    await driver.switchTo().frame(1)
    await driver.findElement(By.name("partial_ind")).click()
    await driver.findElement(By.name("last_name")).click()
    await driver.findElement(By.name("last_name")).sendKeys(firstLetter)
    await driver.findElement(By.name("begin_date")).click()
    await driver.findElement(By.name("begin_date")).sendKeys("01-NOV-2021")
    await driver.findElement(By.css("tr:nth-child(7) > td:nth-child(1)")).click()
    await driver.findElement(By.name("end_date")).click()
    await driver.findElement(By.name("end_date")).sendKeys("14-NOV-2021")
    await driver.findElement(By.name("case_type")).click()
    await driver.findElement(By.css("option:nth-child(17)")).click()
    await driver.findElement(By.css("input:nth-child(4)")).click()
    await driver.switchTo().frame(1)
        // Firefox fails here with "NoSuchWindowError: Browsing context has been discarded"
    console.log(await driver.findElement(By.css("tr:nth-child(2) > td:nth-child(1)")).getText())
  }
  async scrapeData() {
    const TIMEOUT_IN_SECONDS = 30 * 1000
    let driver = await new Builder().forBrowser('chrome').build()
    await driver.manage().setTimeouts( { implicit: TIMEOUT_IN_SECONDS, pageLoad: TIMEOUT_IN_SECONDS, script: TIMEOUT_IN_SECONDS } )
    for (let letter of ['A']) {
      await this.scrapeByFirstLetter(driver, letter)
    }
    await driver.quit();
  }
}
new Scraper().scrapeData()
